extends SceneTree

func _init() -> void:
    var validation := ContentValidation.validate()
    assert(validation.valid)
    assert(validation.heroes == 4)
    assert(validation.cards == 16)
    assert(validation.arenas == 15)

    var energy := EnergyPool.new()
    energy.configure(10.0, 1.5)
    assert(energy.can_spend(4.0))
    assert(energy.spend(4.0))
    assert(is_equal_approx(energy.current, 6.0))
    assert(not energy.can_spend(7.0))
    energy.tick(1.5)
    assert(is_equal_approx(energy.current, 7.0))

    var arena := ArenaState.new()
    arena.add_hazard("test", 1.0, 1.0)
    assert(arena.active_hazards.size() == 1)
    arena.tick(0.5)
    assert(arena.active_hazards.size() == 1)
    arena.tick(0.5)
    assert(arena.active_hazards.is_empty())
    assert(arena.destroy_tile(0, 0) == ArenaState.Tile.CRACKED)
    assert(arena.destroy_tile(0, 0) == ArenaState.Tile.COLLAPSED)
    assert(arena.destroy_tile(0, 0) == ArenaState.Tile.ABYSS)

    var rules := ArenaRules.resolve_element_interaction("water", "electricity")
    assert(rules.reaction == "shock_zone")

    var enemy := ArenaEnemy.new()
    enemy.configure(ArenaEnemy.Role.CHASER, 100.0, 10.0, 100.0, 0.0)
    enemy.position = Vector2(100, 0)
    enemy.apply_slow(0.5, 2.0)
    enemy.move_toward_target(Vector2(200, 0), 1.0)
    assert(is_equal_approx(enemy.position.x, 150.0))
    enemy.tick(2.0)
    assert(is_equal_approx(enemy.slow_multiplier, 1.0))

    var state := MatchState.new()
    state.configure(90.0, 180.0, 240.0)
    state.tick(181.0)
    assert(state.phase == MatchState.Phase.CATACLYSM)
    state.tick(59.0)
    assert(state.is_result())

    var hero := ArenaHero.new()
    hero.configure(HeroDefinitions.initial()[0])
    var build := BuildState.new()
    var upgrade := UpgradeOffer.new("test", "common", {"damage": 4.0, "max_hp": 10.0})
    assert(build.apply_upgrade(upgrade))
    build.apply_to_hero(hero)
    assert(is_equal_approx(hero.damage, hero.base_damage + 4.0))
    assert(is_equal_approx(hero.max_hp, hero.base_hp + 10.0))

    print("ARENA_FORGE_ENGINE_CONTRACTS_OK")
    quit()
